# Generated by Django 5.1.4 on 2025-02-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shopCart',
        ),
    ]
