# Generated by Django 5.1.4 on 2025-02-07 13:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_favoutite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favoutite',
            new_name='Favourite',
        ),
    ]
